In [1]:
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
data = np.genfromtxt('admissionData.txt',delimiter=',')

In [4]:
examData = data[:,0:2]
admit = data[:,2]

In [6]:
logreg = sk.linear_model.LogisticRegression()

In [7]:
logreg.fit(examData,admit)

C:\Users\Cory\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
logreg.predict(examData)

array([0., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.sum(logreg.predict(examData)==admit)

87

In [10]:
(np.sum(logreg.predict(examData)==admit))/len(examData)

0.87

In [12]:
logreg.predict(np.array([48,63]).reshape(1,-1))

array([0.])

In [13]:
exam1 = np.array([47,58,65])
exam2 = np.array([65,58,47])

In [15]:
logreg.predict(np.stack([exam1,exam2],axis=1))

array([0., 1., 1.])

In [16]:
logreg.predict_proba(np.stack([exam1,exam2],axis=1))

array([[0.51915716, 0.48084284],
       [0.4677705 , 0.5322295 ],
       [0.48575218, 0.51424782]])

In [17]:
e1 = np.array([90,95,98,90,95,48,90,30])
e2 = np.array([95,90,90,98,48,95,30,90])

In [19]:
logreg.predict(np.stack([e1,e2],axis=1))

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
logreg.predict_proba(np.stack([e1,e2],axis=1))

array([[0.0753677 , 0.9246323 ],
       [0.07282057, 0.92717943],
       [0.06540693, 0.93459307],
       [0.06913373, 0.93086627],
       [0.22419766, 0.77580234],
       [0.29062819, 0.70937181],
       [0.37970234, 0.62029766],
       [0.48869302, 0.51130698]])